services:
  api:
    container_name: pokeapi
    image: ignaciochalub/pokeapi-graphql
    ports: 
      - 4000:4000
    env_file: .env
    depends_on:
      - database
  database:
    container_name: database
    image: postgres:14.1-alpine
    restart: always
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
volumes:
    database:
        driver: local