services:
  api:
    container_name: pokeapi
    image: ignaciochalub/pokeapi-graphql
    ports: 
      - 8080:4000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/pokeapi-graphql
    depends_on:
      - database
  database:
    container_name: database
    image: postgres:14.1-alpine
    restart: always
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
volumes:
    database:
        driver: local